#!/bin/bash

sudo touch /var/log/update_script.log
upd=$(sudo apt-get update && sudo apt-get upgrade)
echo "$upd" | sudo tee -a /var/log/update_script.log
crontab -l 2>/dev/null; echo "0 4 * * 1 ~/init/scripts/02" | crontab -

			
