#!/bin/bash

postfix_if_install=(which postfix)
if [[ -z $postfix_if_install ]]
then
	sudo apt-get install sendmail
	sudo apt-get install postfix
	sudo mkifo /var/spool/postfix/public/pickup
	sudo service postfix restart
fi
crontab -l 2>/dev/null; echo "0 0 * * * ~/init/scripts/04" | crontab -
sudo touch /etc/cron_hash_check
sudo chmod 666 /etc/cron_hash_check
hash_check=$(sudo md5sum -c /etc/cron_hash_check | grep -o "FAILED")
echo $hash_check
if [[ -z $hash_check ]]
then
    sudo md5sum /etc/crontab > /etc/cron_hash_check
    exit 0
fi
if [[ $hash_check == "FAILED" ]]
then
	touch /tmp/mail.txt
	echo "Mom, i'm sending email" > /tmp/mail.txt
	sudo sendmail root < /tmp/mail.txt
	sudo rm -rf /tmp/mail.txt
	sudo md5sum /etc/crontab > /etc/cron_hash_check
fi
